### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by achillesrasquinha** [achillesrasquinha/16SMaRT#1]
### Description

- [x] #2
- [x] Data Logger for Data Dump
- [x] Error Issues
- [x] Check where CSV data is fetched from.
- [x] Check if SRA already exists.
- [x] Check if FASTQ already exists.
- [x] `mothur` acting poorly with grouped FASTA files. (Check)
- [x] configure SILVA version
- [ ] Create Status check.
- [ ] Build Geo Graph
- [x] Create Base Image for CI
- [ ] Better Data Handling for mothur
- [ ] TQDM + ProcessPool + Build Function
- [x] Add CSV URL getter.
- [ ] Add URL for FASTQ optional.
- [x] Configure Preprocess.
- [x] Perform FastQC after fasterqdump
- [ ] Multiple DataBases (https://github.com/tseemann/sixess)
- [ ] Support GZ and use GZ for minimal output.
- [ ] Support other HPC systems (https://blog.jwf.io/2019/08/hpc-workloads-containers/)
- [ ] Create Flow Diagram
- [ ] Default Truncation Length (`min_length`, `max_length`)
- [ ] Support other based pipelines DADA2, QIIME. Also support 18s + ITS pipelines.

#### Updated
- [x] Issue running FASTQC
- [x] Parallelize Groups
- [x] FASTQC not accepting input

**Comment by furbeck** [comment]
- [ ] Build Geo Graph
